# pages:
#   stage: deploy
#   script:
#     - mkdir .public
#     - cp -r * .public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
#   only:
#     - master

image: ruby:2.7

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - deploy
  - post-deploy-test

before_script:
  - gem install bundler
  - bundle install
  - gem install cucumber
  - gem install selenium-webdriver
  - gem install rspec

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  rules:
    - if: $CI_COMMIT_BRANCH != "master"

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

test:
  stage: post-deploy-test
  script:
    - cucumber
