# pages:
#   stage: deploy
#   script:
#     - mkdir .public
#     - cp -r * .public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
#   only:
#     - master

image: ruby:2.7

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - deploy
  - post-deploy-test

before_script:
  - gem install bundler
  - bundle install
  - gem install cucumber
  - gem install selenium-webdriver
  - gem install rspec
  - gem install chromedriver-helper -v 1.0.0

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  rules:
    - if: $CI_COMMIT_BRANCH != "master"

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

test:
  stage: post-deploy-test
  script:
    # Update apt-get and install pip
    - apt-get update
    - apt-get install -y python3-pip
    # Install robot framework and the selenium library
    - pip3 install robotframework
    - pip3 install robotframework-seleniumlibrary
    # Install the chrome and chrome webdriver
    - apt-get install -y xvfb
    - apt-get install -y zip
    - apt-get install -y wget
    - apt-get install -y ca-certificates
    - apt-get install -y libnss3-dev libasound2 libxss1 libappindicator3-1 libindicator7 gconf-service libgconf-2-4 libpango1.0-0 xdg-utils fonts-liberation libgbm1
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
    - dpkg -i google-chrome*.deb 
    - rm google-chrome*.deb
    - wget -N http://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - chmod +x chromedriver
    - cp chromedriver /usr/local/bin
    - rm chromedriver_linux64.zip
    - rm chromedriver
    - cucumber
